version: "3.8"
   
services:
  db:
    image: postgres:9.6
    hostname: db
    environment:
      - POSTGRES_DB=talentalps
      - POSTGRES_USER=talentalps
      - POSTGRES_PASSWORD=talentalps
  talentalps:
    restart: always
    build: .
    volumes: &talentalps_volumes
      - .:/code
    ports:
      - "8000:8000"
    links: &talentalps_links
      - db
    depends_on:
      - db
    environment: 
      # Django variables
      DJANGO_SETTINGS_MODULE: talentalps.settings
      DEBUG: "True"
      SECRET_KEY: secret
      ALLOWED_HOSTS: '*'
      # Postgres variables
      DB_NAME: talentalps
      DB_USER: talentalps
      DB_PASS: talentalps
      DB_HOST: db
      DB_PORT: 5432
      # DigitalOcean Spaces
      STATIC_ACCESS_KEY_ID: ""
      STATIC_SECRET_KEY: ""
      STATIC_BUCKET_NAME: ""
      STATIC_ENDPOINT_URL: ""
      # Logging
      DJANGO_LOGLEVEL: "info"
    command: start_dev