version: "3"
   
services:
  db:
    image: postgres:12
    hostname: db
    environment:
      - POSTGRES_DB=talentalps
      - POSTGRES_USER=talentalps
      - POSTGRES_PASSWORD=talentalps

  redis:
    image: redis:6.0.9-alpine
    volumes:
      - redis_data:/data
  
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/code/public/static
      - media_volume:/code/media
    depends_on:
      - app
    restart: "on-failure"
    
  app:
    restart: always
    build: .
    volumes: &talentalps_volumes
      - .:/code
      - static_volume:/code/public/static
      - media_volume:/code/media
    ports:
      - 8000:8000
    links: &talentalps_links
      - db
      - redis
    depends_on:
      - db
      - redis
    environment: 
      # Django variables
      DJANGO_SETTINGS_MODULE: talentalps.settings
      DEBUG: "True"
      SECRET_KEY: secret
      ALLOWED_HOSTS: '*'
      # Postgres variables
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: 
      DB_HOST: db
      DB_PORT: 5432
      # DigitalOcean Spaces
      STATIC_ACCESS_KEY_ID: ""
      STATIC_SECRET_KEY: ""
      STATIC_BUCKET_NAME: ""
      STATIC_ENDPOINT_URL: ""
      STATIC_QUERYSTRING_AUTH: "False"
      # Logging
      DJANGO_LOGLEVEL: "info"

      # EMAIL
      # EMAIL_HOST: ""
      # EMAIL_HOST_USER: ""
      # EMAIL_HOST_PASSWORD: ""

      # REDIS
      REDIS_HOST: redis
    command: start_dev

volumes: 
  redis_data:
  static_volume:
  media_volume: