# Generated by Django 3.1.3 on 2020-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=100, verbose_name='status'),
        ),
    ]
