# Generated by Django 3.1.3 on 2020-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_no',
            field=models.CharField(default='123', max_length=150, verbose_name='registration_no'),
            preserve_default=False,
        ),
    ]
