# Generated by Django 3.1.3 on 2020-11-25 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_company_registration_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=user.models.get_company_gallery_image_path, verbose_name='image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
