# Generated by Django 3.1.3 on 2020-11-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_companyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
    ]
