# Generated by Django 3.1.2 on 2020-10-24 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201024_1933'),
        ('user', '0004_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='user',
            new_name='userprofile',
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joblisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.joblisting', verbose_name='job listing')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='user profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
