# Generated by Django 3.1.3 on 2020-11-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_companyimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyimage',
            options={'ordering': ['order']},
        ),
    ]
