# Generated by Django 3.1.2 on 2020-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201024_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(choices=[('MY', 'Malaysia')], default='MY', max_length=50, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('MY', 'Malaysia')], max_length=50, null=True, verbose_name='country'),
        ),
    ]
