# Generated by Django 3.1.2 on 2020-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201025_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_updates',
            field=models.BooleanField(default=False, verbose_name='receive updates'),
        ),
    ]
