# Generated by Django 3.1.3 on 2020-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_receive_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('it_services', 'Information Technology & Services'), ('telecommunications', 'Telecommunications')], max_length=150, verbose_name='industry'),
        ),
    ]
