# Generated by Django 3.1.3 on 2020-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201121_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('Telecommunications', 'Telecommunications'), ('Medical', 'Medical'), ('Actuarial Work, Pensions & Insurance', 'Actuarial Work, Pensions & Insurance'), ('Transport & Logistics', 'Transport & Logistics'), ('Airline/Aviation', 'Airline/Aviation'), ('Legal Services', 'Legal Services'), ('Performing Arts', 'Performing Arts'), ('Scientific Research', 'Scientific Research'), ('Psychology', 'Psychology'), ('Engineering, Manufacturing & Construction', 'Engineering, Manufacturing & Construction'), ('Creative', 'Creative'), ('Financial Management & Accountancy', 'Financial Management & Accountancy'), ('Defence & Public Protection', 'Defence & Public Protection'), ('Languages & TEFL', 'Languages & TEFL'), ('Buying, Selling, Retailing', 'Buying, Selling, Retailing'), ('Charity & Development work', 'Charity & Development work'), ('Publishing', 'Publishing'), ('Education', 'Education'), ('Natural Resources & Environment', 'Natural Resources & Environment'), ('Banking', 'Banking'), ('Government & Politics', 'Government & Politics'), ('Management Consultancy', 'Management Consultancy'), ('Advertising, PR & Marketing', 'Advertising, PR & Marketing'), ('Media', 'Media'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage'), ('Information Technology', 'Information Technology'), ('Social, Guidance, Community', 'Social, Guidance, Community'), ('HR & Recruitment', 'HR & Recruitment'), ('Healthcare & Psychology', 'Healthcare & Psychology'), ('Hospitality & Events Management', 'Hospitality & Events Management')], max_length=150, verbose_name='industry'),
        ),
    ]
