# Generated by Django 3.1.3 on 2020-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201122_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.PositiveIntegerField(verbose_name='founded'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('Scientific Research', 'Scientific Research'), ('Engineering, Manufacturing & Construction', 'Engineering, Manufacturing & Construction'), ('Financial Management & Accountancy', 'Financial Management & Accountancy'), ('Buying, Selling, Retailing', 'Buying, Selling, Retailing'), ('Government & Politics', 'Government & Politics'), ('Actuarial Work, Pensions & Insurance', 'Actuarial Work, Pensions & Insurance'), ('Psychology', 'Psychology'), ('Transport & Logistics', 'Transport & Logistics'), ('Healthcare & Psychology', 'Healthcare & Psychology'), ('Telecommunications', 'Telecommunications'), ('Charity & Development work', 'Charity & Development work'), ('Hospitality & Events Management', 'Hospitality & Events Management'), ('Performing Arts', 'Performing Arts'), ('Natural Resources & Environment', 'Natural Resources & Environment'), ('Social, Guidance, Community', 'Social, Guidance, Community'), ('Media', 'Media'), ('Languages & TEFL', 'Languages & TEFL'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Advertising, PR & Marketing', 'Advertising, PR & Marketing'), ('Defence & Public Protection', 'Defence & Public Protection'), ('Publishing', 'Publishing'), ('Education', 'Education'), ('Information Technology', 'Information Technology'), ('Creative', 'Creative'), ('HR & Recruitment', 'HR & Recruitment'), ('Management Consultancy', 'Management Consultancy'), ('Legal Services', 'Legal Services'), ('Airline/Aviation', 'Airline/Aviation'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage')], max_length=150, verbose_name='industry'),
        ),
    ]
