# Generated by Django 3.1.3 on 2020-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201122_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=150, verbose_name='industry'),
        ),
    ]
