# Generated by Django 3.1.3 on 2020-11-22 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0002_auto_20201123_0353'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationNotification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('interview', 'Interview has been set!'), ('approved', 'Job Application has been approved!'), ('declined', 'Unfortunately, your job application has been declined.')], max_length=100, verbose_name='type')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                ('jobapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication', verbose_name='job application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
