# Generated by Django 3.1.2 on 2020-10-24 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201024_1933'),
        ('user', '0004_searchhistory'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                ('jobapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication', verbose_name='job application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='employernotification',
            name='employer',
        ),
        migrations.DeleteModel(
            name='CandidateNotification',
        ),
        migrations.DeleteModel(
            name='EmployerNotification',
        ),
    ]
