# Generated by Django 3.1.2 on 2020-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20201024_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationnotification',
            name='type',
            field=models.CharField(choices=[('interview', 'Interview has been set!'), ('approved', 'Job Application has been approved!'), ('declined', 'Unfortunately, your job application has been declined.')], default='declined', max_length=100, verbose_name='type'),
            preserve_default=False,
        ),
    ]
