# Generated by Django 3.1.2 on 2020-10-24 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_searchhistory'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('joblisting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.joblisting', verbose_name='job listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('virtual', 'Virtual/Online Interview'), ('meetup', 'In Person Interview'), ('other', 'Other')], max_length=80, verbose_name='interview type'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview Set'), ('complete', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=50, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=300, verbose_name='question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateQuestionnaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=300, verbose_name='question')),
                ('answer', models.TextField(max_length=400, verbose_name='answer')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate', verbose_name='candidate')),
                ('jobapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication', verbose_name='job application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
