# Generated by Django 3.1.3 on 2020-11-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate', verbose_name='candidate'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='joblisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.joblisting', verbose_name='job listing'),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate', verbose_name='candidate'),
        ),
        migrations.AddField(
            model_name='interview',
            name='jobapplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication', verbose_name='job application'),
        ),
        migrations.AddField(
            model_name='candidatequestionnaireanswer',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate', verbose_name='candidate'),
        ),
        migrations.AddField(
            model_name='candidatequestionnaireanswer',
            name='jobapplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication', verbose_name='job application'),
        ),
    ]
