# Generated by Django 3.1.2 on 2020-10-24 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201024_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1800),
        ),
    ]
