# Generated by Django 3.1.3 on 2020-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_joblisting_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
