# Generated by Django 3.1.3 on 2020-11-30 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_joblisting_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='requirements_description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibilities_description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
