# Generated by Django 3.1.2 on 2020-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201025_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='country',
            field=models.CharField(choices=[('MY', 'Malaysia')], max_length=80, verbose_name='country'),
        ),
    ]
