# Generated by Django 3.1.3 on 2020-11-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20201130_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='title',
        ),
    ]
