# Generated by Django 3.1.3 on 2020-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201201_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, max_length=120, verbose_name='question'),
        ),
    ]
