# Generated by Django 3.1.3 on 2020-12-03 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201201_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 21, 57, 39, 328694), verbose_name='expiry date'),
        ),
    ]
