# Generated by Django 3.1.3 on 2020-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201116_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(choices=[('telecommunications', 'Telecommunications'), ('it_services', 'Information Technology & Services')], max_length=80, verbose_name='industry'),
        ),
    ]
