# Generated by Django 3.1.3 on 2020-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20201118_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(choices=[('Scientific Research', 'Scientific Research'), ('Publishing', 'Publishing'), ('Actuarial Work, Pensions & Insurance', 'Actuarial Work, Pensions & Insurance'), ('Charity & Development work', 'Charity & Development work'), ('Performing Arts', 'Performing Arts'), ('Telecommunications', 'Telecommunications'), ('Media', 'Media'), ('Natural Resources & Environment', 'Natural Resources & Environment'), ('Information Technology', 'Information Technology'), ('Advertising, PR & Marketing', 'Advertising, PR & Marketing'), ('Languages & TEFL', 'Languages & TEFL'), ('Healthcare & Psychology', 'Healthcare & Psychology'), ('Buying, Selling, Retailing', 'Buying, Selling, Retailing'), ('Government & Politics', 'Government & Politics'), ('HR & Recruitment', 'HR & Recruitment'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage'), ('Financial Management & Accountancy', 'Financial Management & Accountancy'), ('Creative', 'Creative'), ('Transport & Logistics', 'Transport & Logistics'), ('Banking', 'Banking'), ('Legal Services', 'Legal Services'), ('Management Consultancy', 'Management Consultancy'), ('Medical', 'Medical'), ('Social, Guidance, Community', 'Social, Guidance, Community'), ('Airline/Aviation', 'Airline/Aviation'), ('Defence & Public Protection', 'Defence & Public Protection'), ('Education', 'Education'), ('Psychology', 'Psychology'), ('Engineering, Manufacturing & Construction', 'Engineering, Manufacturing & Construction'), ('Hospitality & Events Management', 'Hospitality & Events Management')], max_length=80, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_functions',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Accounting', 'Accounting'), ('Healthcare', 'Healthcare'), ('Human Resources (HR)', 'Human Resources (HR)'), ('Retail', 'Retail'), ('Public Service & Security', 'Public Service & Security'), ('Property Management', 'Property Management'), ('Legal', 'Legal'), ('Customer Service', 'Customer Service'), ('Supply Chain & Logistics', 'Supply Chain & Logistics'), ('Marketing', 'Marketing'), ('Media & Public Relations (PR)', 'Media & Public Relations (PR)'), ('Production', 'Production'), ('Real Estate', 'Real Estate'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Administrative', 'Administrative'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Hospitality & Tourism', 'Hospitality & Tourism')], max_length=80, verbose_name='job functions'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('associate', 'Associate Level'), ('senior', 'Senior Level'), ('director', 'Director Level'), ('executive', 'Executive Level')], max_length=50, verbose_name='level'),
        ),
    ]
