# Generated by Django 3.1.3 on 2020-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20201122_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(choices=[('Scientific Research', 'Scientific Research'), ('Engineering, Manufacturing & Construction', 'Engineering, Manufacturing & Construction'), ('Financial Management & Accountancy', 'Financial Management & Accountancy'), ('Buying, Selling, Retailing', 'Buying, Selling, Retailing'), ('Government & Politics', 'Government & Politics'), ('Actuarial Work, Pensions & Insurance', 'Actuarial Work, Pensions & Insurance'), ('Psychology', 'Psychology'), ('Transport & Logistics', 'Transport & Logistics'), ('Healthcare & Psychology', 'Healthcare & Psychology'), ('Telecommunications', 'Telecommunications'), ('Charity & Development work', 'Charity & Development work'), ('Hospitality & Events Management', 'Hospitality & Events Management'), ('Performing Arts', 'Performing Arts'), ('Natural Resources & Environment', 'Natural Resources & Environment'), ('Social, Guidance, Community', 'Social, Guidance, Community'), ('Media', 'Media'), ('Languages & TEFL', 'Languages & TEFL'), ('Medical', 'Medical'), ('Banking', 'Banking'), ('Advertising, PR & Marketing', 'Advertising, PR & Marketing'), ('Defence & Public Protection', 'Defence & Public Protection'), ('Publishing', 'Publishing'), ('Education', 'Education'), ('Information Technology', 'Information Technology'), ('Creative', 'Creative'), ('HR & Recruitment', 'HR & Recruitment'), ('Management Consultancy', 'Management Consultancy'), ('Legal Services', 'Legal Services'), ('Airline/Aviation', 'Airline/Aviation'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage')], max_length=80, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_functions',
            field=models.CharField(choices=[('Property Management', 'Property Management'), ('Media & Public Relations (PR)', 'Media & Public Relations (PR)'), ('Supply Chain & Logistics', 'Supply Chain & Logistics'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Accounting', 'Accounting'), ('Legal', 'Legal'), ('Retail', 'Retail'), ('Engineering', 'Engineering'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Marketing', 'Marketing'), ('Human Resources (HR)', 'Human Resources (HR)'), ('Real Estate', 'Real Estate'), ('Education', 'Education'), ('Production', 'Production'), ('Public Service & Security', 'Public Service & Security'), ('Administrative', 'Administrative'), ('Customer Service', 'Customer Service'), ('Sales', 'Sales')], max_length=80, verbose_name='job functions'),
        ),
    ]
