# Generated by Django 3.1.3 on 2020-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20201122_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(choices=[('Management Consultancy', 'Management Consultancy'), ('Creative', 'Creative'), ('Social, Guidance, Community', 'Social, Guidance, Community'), ('Financial Management & Accountancy', 'Financial Management & Accountancy'), ('Media', 'Media'), ('Hospitality & Events Management', 'Hospitality & Events Management'), ('Telecommunications', 'Telecommunications'), ('Airline/Aviation', 'Airline/Aviation'), ('HR & Recruitment', 'HR & Recruitment'), ('Languages & TEFL', 'Languages & TEFL'), ('Engineering, Manufacturing & Construction', 'Engineering, Manufacturing & Construction'), ('Government & Politics', 'Government & Politics'), ('Charity & Development work', 'Charity & Development work'), ('Banking', 'Banking'), ('Natural Resources & Environment', 'Natural Resources & Environment'), ('Performing Arts', 'Performing Arts'), ('Information Technology', 'Information Technology'), ('Advertising, PR & Marketing', 'Advertising, PR & Marketing'), ('Scientific Research', 'Scientific Research'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage'), ('Actuarial Work, Pensions & Insurance', 'Actuarial Work, Pensions & Insurance'), ('Healthcare & Psychology', 'Healthcare & Psychology'), ('Publishing', 'Publishing'), ('Transport & Logistics', 'Transport & Logistics'), ('Buying, Selling, Retailing', 'Buying, Selling, Retailing'), ('Medical', 'Medical'), ('Legal Services', 'Legal Services'), ('Psychology', 'Psychology'), ('Education', 'Education'), ('Defence & Public Protection', 'Defence & Public Protection')], max_length=80, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_functions',
            field=models.CharField(choices=[('Public Service & Security', 'Public Service & Security'), ('Property Management', 'Property Management'), ('Customer Service', 'Customer Service'), ('Supply Chain & Logistics', 'Supply Chain & Logistics'), ('Accounting', 'Accounting'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Healthcare', 'Healthcare'), ('Legal', 'Legal'), ('Production', 'Production'), ('Retail', 'Retail'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Sales', 'Sales'), ('Engineering', 'Engineering'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Administrative', 'Administrative'), ('Real Estate', 'Real Estate'), ('Human Resources (HR)', 'Human Resources (HR)'), ('Education', 'Education'), ('Media & Public Relations (PR)', 'Media & Public Relations (PR)')], max_length=80, verbose_name='job functions'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
