# Generated by Django 3.1.3 on 2020-11-22 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20201123_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
