# Generated by Django 3.1.3 on 2020-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20201123_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(max_length=500, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_functions',
            field=models.CharField(max_length=500, verbose_name='job functions'),
        ),
    ]
